# Generated by Django 4.1.3 on 2022-11-22 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_category_videos_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos_posted',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
