# Generated by Django 4.1.3 on 2022-11-25 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_profile_videos_videos_posted_video_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos_posted',
            name='video_liked',
            field=models.ManyToManyField(blank=True, related_name='video_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
